#!/usr/bin/env bash
# Edison Shared Hook Guard
# This script provides unified session detection for all Edison hooks.
# Generated by Edison - do not edit directly.

# edison_hook_guard - Unified session gating function
#
# Usage: edison_hook_guard "<hook_id>" "<execution_scope>"
#
# Arguments:
#   hook_id         - The hook identifier (for logging)
#   execution_scope - One of: "session", "project", "always"
#
# Behavior:
#   - "session": Exit 0 (skip hook) if no Edison session is detected
#   - "project": Always continue (any Edison project)
#   - "always":  Always continue (even outside Edison projects)
#
# Returns:
#   - Exits 0 to skip hook execution (no session and scope=session)
#   - Returns (continues) to allow hook execution
#
edison_hook_guard() {
    local hook_id="${1:-unknown}"
    local scope="${2:-session}"

    # "always" scope: never skip
    if [[ "$scope" == "always" ]]; then
        return 0
    fi

    # "project" scope: continue if Edison is available (don't require active session)
    if [[ "$scope" == "project" ]]; then
        return 0
    fi

    # "session" scope: require active Edison session
    # Check env var first (fastest)
    if [[ -n "${AGENTS_SESSION:-}" ]] || [[ -n "${EDISON_SESSION_ID:-}" ]]; then
        return 0
    fi

    # Fall back to CLI detection (handles .session-id file and worktree detection)
    if command -v edison >/dev/null 2>&1; then
        local session_found
        session_found=$(edison session detect --json 2>/dev/null | grep -o '"sessionFound":[^,}]*' | cut -d: -f2 | tr -d ' ')
        if [[ "$session_found" == "true" ]]; then
            return 0
        fi
    fi

    # No session detected and scope=session: skip this hook
    exit 0
}